//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Lang.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة طلب.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string CuName {
            get {
                return ResourceManager.GetString("CuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف صنف.
        /// </summary>
        public static string ItmDel {
            get {
                return ResourceManager.GetString("ItmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الصنف.
        /// </summary>
        public static string ItmDesc {
            get {
                return ResourceManager.GetString("ItmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صنف.
        /// </summary>
        public static string ItmEd {
            get {
                return ResourceManager.GetString("ItmEd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصنف.
        /// </summary>
        public static string ItmId {
            get {
                return ResourceManager.GetString("ItmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج اطلب.
        /// </summary>
        public static string OrAp {
            get {
                return ResourceManager.GetString("OrAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف طلب.
        /// </summary>
        public static string OrDel {
            get {
                return ResourceManager.GetString("OrDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الطلب.
        /// </summary>
        public static string OrDet {
            get {
                return ResourceManager.GetString("OrDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل طلب.
        /// </summary>
        public static string OrEd {
            get {
                return ResourceManager.GetString("OrEd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلبية.
        /// </summary>
        public static string OrId {
            get {
                return ResourceManager.GetString("OrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الاصناف.
        /// </summary>
        public static string OrItm {
            get {
                return ResourceManager.GetString("OrItm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلب الان.
        /// </summary>
        public static string OrNow {
            get {
                return ResourceManager.GetString("OrNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلب الان 3 اصناف او اكثر واحصل على 15% خصم.
        /// </summary>
        public static string OrNowDisc {
            get {
                return ResourceManager.GetString("OrNowDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الطلب.
        /// </summary>
        public static string OrVew {
            get {
                return ResourceManager.GetString("OrVew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجمالي.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
